### PR TITLE
Fix run

### PR DESCRIPTION
**Pull request by ctrlcctrlv**

### CODE REVIEW

**Review by alerque — APPROVED** [review]

**Comment by alerque** [comment]
Should I tag a patch release to get this out? I don't foresee myself working on this in the immediate future so if there is nothing else pending on your radar we should probably just go ahead publish a patch tag.

**Comment by ctrlcctrlv** [comment]
Yes you should. Sorry for the inconvenience caused.

**Comment by ctrlcctrlv** [comment]
I really don't know how this happened at all but speculate in the commit message:

> Probably I was using the `-e` flag and testing on an installed version rather than the Git version, oops.

The machine I had this installed on before, I no longer have. Gave it to a fellow fossie.

**Comment by alerque** [comment]
No worries, the release workflow is pretty easy on this one.

**Pull request merged**
