### PR TITLE
Remove repeated AnchorPoint's when the repetition is impossible

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
While this library is often very good at normalization, @EwonRael's Besley contains a brand new horrible FontForge bug:
```sfd
StartChar: A
…
AnchorPoint: "Anchor-2" 1396 0 basechar 0
AnchorPoint: "Anchor-1" 796 0 basechar 0
AnchorPoint: "Anchor-0" 864 1500 basechar 0
AnchorPoint: "Anchor-2" 1396 0 basechar 0
AnchorPoint: "Anchor-1" 796 0 basechar 0
AnchorPoint: "Anchor-0" 864 1500 basechar 0
AnchorPoint: "Anchor-3" 1396 0 basechar 0
AnchorPoint: "Anchor-2" 796 0 basechar 0
AnchorPoint: "Anchor-0" 864 1500 basechar 0
…
EndChar
```
https://github.com/indestructible-type/Besley/blob/master/sources/fontforge/Besley-Book.sfd#L638-L696

This bug is particularly difficult to solve in FontForge itself, as I'm not the font's author and cannot even guess how this broken state was created, it's highly unlikely to be Owen's fault and is likely an undiscovered FontForge bug (or one of the thousands of unsolved ones).

But created it was, and this causes UFO's generated to have duplicate anchor points (w/same class name), which causes `fontmake` to fail to build.

I have solved this issue, but it took a lot of doing.

This library is now a dependency of sfdnormalize: https://github.com/ctrlcctrlv/sfdutf7.py

Because those quoted strings…they're not normal. They're SFDUTF7, which isn't UTF-7. See my lib page for more info.

In any event…

Before:
```sfd
StartChar: A
Encoding: 65 65 12
Width: 1720
Flags: HMW
AnchorPoint: "Anchor-2" 1396 0 basechar 0
AnchorPoint: "Anchor-1" 796 0 basechar 0
AnchorPoint: "Anchor-0" 864 1500 basechar 0
AnchorPoint: "Anchor-2" 1396 0 basechar 0
AnchorPoint: "Anchor-1" 796 0 basechar 0
AnchorPoint: "Anchor-0" 864 1500 basechar 0
AnchorPoint: "Anchor-3" 1396 0 basechar 0
AnchorPoint: "Anchor-2" 796 0 basechar 0
AnchorPoint: "Anchor-0" 864 1500 basechar 0
LayerCount: 2
Fore
SplineSet
816 1252 m 2
 524 578 l 2
 514 554 516 550 552 550 c 2
 1058 550 l 2
 1119 550 1112 553 1096 596 c 2
 848 1246 l 2
 833 1286 831 1286 816 1252 c 2
0 42 m 2
 0 84 l 2
 0 104 6 110 28 110 c 2
 154 110 l 2
 196 110 203 122 215 150 c 2
 808 1500 l 2
 812 1509 816 1510 829 1510 c 2
 909 1510 l 2
 925 1510 931 1509 935 1498 c 2
 1478 154 l 2
 1491 122 1488 110 1534 110 c 2
 1692 110 l 2
 1719 110 1720 106 1720 79 c 2
 1720 35 l 2
 1720 4 1719 0 1688 0 c 2
 1098 0 l 2
 1072 0 1060 3 1060 32 c 2
 1060 78 l 2
 1060 106 1070 110 1096 110 c 2
 1248 110 l 2
 1280 110 1272 127 1265 146 c 2
 1175 386 l 2
 1158 431 1160 440 1096 440 c 2
 516 440 l 2
 470 440 462 431 449 400 c 2
 346 158 l 2
 332 126 333 110 377 110 c 2
 528 110 l 2
 552 110 560 105 560 80 c 2
 560 32 l 2
 560 0 560 0 528 0 c 2
 50 0 l 2
 13 0 0 2 0 42 c 2
EndSplineSet
Substitution2: "'c2sc' Capitals to Small Capitals in Latin lookup 1 subtable" a.sc                                                                                                                                                                  
EndChar                                                                                                                                                                                                                                             
 ```

After:
```sfd
StartChar: A
Encoding: 65 65 12
Width: 1720
Flags: MW
AnchorPoint: "Anchor-0" 864 1500 basechar 0
AnchorPoint: "Anchor-1" 796 0 basechar 0
AnchorPoint: "Anchor-2" 1396 0 basechar 0
AnchorPoint: "Anchor-2" 796 0 basechar 0
AnchorPoint: "Anchor-3" 1396 0 basechar 0
ForeSplineSet
816 1252 m 2
 524 578 l 2
 514 554 516 550 552 550 c 2
 1058 550 l 2    
 1119 550 1112 553 1096 596 c 2
 848 1246 l 2
 833 1286 831 1286 816 1252 c 2
0 42 m 2
 0 84 l 2
 0 104 6 110 28 110 c 2
 154 110 l 2 
 196 110 203 122 215 150 c 2   
 808 1500 l 2
 812 1509 816 1510 829 1510 c 2
 909 1510 l 2
 925 1510 931 1509 935 1498 c 2
 1478 154 l 2
 1491 122 1488 110 1534 110 c 2
 1692 110 l 2
 1719 110 1720 106 1720 79 c 2 
 1720 35 l 2 
 1720 4 1719 0 1688 0 c 2
 1098 0 l 2 
 1072 0 1060 3 1060 32 c 2
 1060 78 l 2
 1060 106 1070 110 1096 110 c 2
 1248 110 l 2
 1280 110 1272 127 1265 146 c 2
 1175 386 l 2
 1158 431 1160 440 1096 440 c 2
 516 440 l 2
 470 440 462 431 449 400 c 2
 346 158 l 2
 332 126 333 110 377 110 c 2
 528 110 l 2
 552 110 560 105 560 80 c 2
 560 32 l 2
 560 0 560 0 528 0 c 2
 50 0 l 2
 13 0 0 2 0 42 c 2
EndSplineSet
Substitution2: "'c2sc' Capitals to Small Capitals in Latin lookup 1 subtable" a.sc
EndChar
```

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Sigh, it needs to just consider the last one, I thought it might be *only* duplicating, not so.

```sfd
AnchorPoint: "Anchor-2" 1396 0 basechar 0
AnchorPoint: "Anchor-2" 796 0 basechar 0
```

I will push an amendment

**Comment by ctrlcctrlv** [comment]
Fixed in 827931c2c0282d16f446caf51a7c4d635ab189a3.

```sfd
StartChar: A    
Encoding: 65 65 12
Width: 1720    
Flags: MW
AnchorPoint: "Anchor-0" 864 1500 basechar 0
AnchorPoint: "Anchor-1" 796 0 basechar 0
AnchorPoint: "Anchor-2" 796 0 basechar 0
AnchorPoint: "Anchor-3" 1396 0 basechar 0
```

**Review by alerque — APPROVED** [review]

**Comment by alerque** [comment]
Did I handle that merge conflict from #12 that I merged first correctly here?

**Comment by ctrlcctrlv** [comment]
I'd put the should_drop after the skip_lines.

**Pull request merged**
